# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Accelerometer Artifact Correction
#'
#' This function corrects abnormally high count values in minute-to-minute 
#' accelerometer data by replacing such values with the average of the 
#' neighboring count values. An integer vector is returned despite the average 
#' calculation often producing a decimal. This follows the convention used by 
#' the NCI's SAS programs 
#' (\url{http://riskfactor.cancer.gov/tools/nhanes_pam}). 
#' 
#' @param counts Integer vector with accelerometer count values.
#' @param thresh Integer value specifying the smallest count value that should 
#' be considered an artifact.
#'
#'
#' @return Integer vector with artifacts corrected.
#' 
#' 
#' @references 
#' National Cancer Institute. Risk factor monitoring and methods: SAS programs 
#' for analyzing NHANES 2003-2004 accelerometer data. Available at: 
#' \url{http://riskfactor.cancer.gov/tools/nhanes_pam}. Accessed March 9, 2018.
#' 
#' Acknowledgment: This material is based upon work supported by the National 
#' Science Foundation Graduate Research Fellowship under Grant No. DGE-0940903.
#'
#'
#' @examples
#' # Load toy dataset
#' data(unidata)
#' 
#' # Get data from ID number 21007
#' counts.part3 <- unidata[unidata[, "seqn"] == 21007, "paxinten"]
#' 
#' # Replace counts > 10,000 with average of neighboring values
#' counts.part3.corrected <- artifacts(counts = counts.part3, thresh = 10000)
#'
#'@export
artifacts <- function(counts, thresh) {
    .Call(`_accelerometry_artifacts`, counts, thresh)
}

