# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Accelerometer Artifact Correction
#'
#' This function corrects abnormally high count values in minute-to-minute 
#' accelerometer data by replacing such values with the average of the 
#' neighboring count values. An integer vector is returned despite the average 
#' calculation often producing a decimal. This follows the convention used by 
#' the NCI's SAS programs 
#' (\url{http://riskfactor.cancer.gov/tools/nhanes_pam}). 
#' 
#' @param counts Integer vector with accelerometer count values.
#' @param thresh Integer value specifying the smallest count value that should 
#' be considered an artifact.
#'
#'
#' @return Integer vector with artifacts corrected.
#' 
#' 
#' @references 
#' National Cancer Institute. Risk factor monitoring and methods: SAS programs 
#' for analyzing NHANES 2003-2004 accelerometer data. Available at: 
#' \url{http://riskfactor.cancer.gov/tools/nhanes_pam}. Accessed March 9, 2018.
#' 
#' Acknowledgment: This material is based upon work supported by the National 
#' Science Foundation Graduate Research Fellowship under Grant No. DGE-0940903.
#'
#'
#' @examples
#' # Load toy dataset
#' data(unidata)
#' 
#' # Get data from ID number 21007
#' counts.part3 <- unidata[unidata[, "seqn"] == 21007, "paxinten"]
#' 
#' # Replace counts > 10,000 with average of neighboring values
#' counts.part3.corrected <- artifacts(counts = counts.part3, thresh = 10000)
#'
#'@export
artifacts <- function(counts, thresh) {
    .Call(`_accelerometry_artifacts`, counts, thresh)
}

#' Activity Bout Detection
#' 
#' Identify bouts of physical activity in uniaxial accelerometer count data.
#' 
#' If \code{nci = FALSE}, the algorithm uses a moving window to go through 
#' every possible interval of length \code{bout_length} in \code{counts}. Any 
#' interval in which all counts are >= \code{tol_lower} and <= 
#' \code{tol_upper}, and no more than \code{tol} counts are less than 
#' \code{thresh_lower} or greater than \code{thresh_upper}, is classified as an 
#' activity bout.
#' 
#' If \code{nci = TRUE}, activity bouts are classified according to the 
#' algorithm used in the NCI's SAS programs. Briefly, this algorithm defines an 
#' activity bout as an interval of length \code{bout_length} that starts with a 
#' count value in \code{[thresh_lower, thresh_upper]} and has no more than 
#' \code{tol} counts outside of that range. If these criteria are met, the bout 
#' continues until there are \code{(tol + 1)} consecutive minutes outside of 
#' \code{[thresh_lower, thresh_upper]}. The parameters \code{tol_lower} and 
#' \code{tol_upper} are not used.
#' 
#' If the user allows for a tolerance (e.g. \code{tol = 2}) and does not use 
#' the NCI algorithm (i.e. \code{nci = FALSE}), specifying a non-zero value for 
#' \code{tol_lower} is highly recommended. Otherwise the algorithm will tend to 
#' classify minutes immediately before and after an activity bout as being part 
#' of the bout.
#' 
#' Specifying \code{thresh_lower} while using an arbitrarily large value for 
#' \code{thresh_upper} is generally recommended. Specifying both of these 
#' parameters can be overly restrictive in that the algorithm may miss bouts of 
#' activity in which counts are consistently high, but not exclusively in one 
#' intensity range.
#' 
#' 
#' @inheritParams artifacts
#' 
#' @param weartime Integer vector with 1's for wear time minutes and 0's for 
#' non-wear time minutes.
#' 
#' @param bout_length Integer value specifying minimum length of an activity 
#' bout.
#' 
#' @param thresh_lower Integer value specifying lower bound for count values to 
#' be included for the intensity level. 
#' 
#' @param thresh_upper Integer value specifying upper bound for count values to 
#' be included for the intensity level.
#' 
#' @param tol Integer value specifying number of minutes with count values 
#' outside of [\code{thresh_lower}, \code{thresh_upper}] to allow during an 
#' activity bout.
#' 
#' @param tol_lower Integer value specifying lower cut-off for count values 
#' outside of intensity range during an activity bout.
#' 
#' @param tol_upper Integer value specifying upper cut-off for count values 
#' outside of intensity range during an activity bout.
#' 
#' @param nci Logical value for whether to use algorithm from the NCI's SAS 
#' programs. See \bold{Details}.
#' 
#' @param days_distinct Logical value for whether to treat each day of data as 
#' distinct, i.e. identify non-wear time and activity bouts for day 1, then day 
#' 2, etc. If \code{FALSE}, algorithm is applied to full monitoring period 
#' continuously. If protocol has participants remove accelerometer for sleep, 
#' strongly recommend setting to \code{FALSE} to capture non-wear periods that 
#' start between 11 pm and midnight. Function assumes that first 1440 data 
#' points are day 1, next 1440 are day 2, and so on.
#' 
#' 
#' @return Integer vector with 1's for minutes that are part of an activity 
#' bout and 0's for minutes that are not.
#' 
#' 
#' @inherit artifacts references
#' 
#' 
#' @examples
#' # Load toy dataset
#' data(unidata)
#' 
#' # Get data from ID number 21005
#' counts.part1 <- unidata[unidata[, "seqn"] == 21005, "paxinten"]
#' 
#' # Identify periods of valid wear time
#' # weartime.flag <- weartime(counts = counts.part1)
#' 
#' # Identify moderate-to-vigorous activity bouts
#' mvpa.bouts <- bouts(counts = counts.part1,
#'                     thresh_lower = 2020)
#' 
#' 
#' @export
bouts <- function(counts, weartime = NULL, bout_length = 10L, thresh_lower = 0L, thresh_upper = 100000L, tol = 0L, tol_lower = 0L, tol_upper = 100000L, nci = TRUE, days_distinct = FALSE) {
    .Call(`_accelerometry_bouts`, counts, weartime, bout_length, thresh_lower, thresh_upper, tol, tol_lower, tol_upper, nci, days_distinct)
}

